app = "pathsix-backend"
primary_region = "dfw"

[env]
  PORT = "8000"
  STORAGE_ROOT = "/data/storage"

[[mounts]]
  source = "vault_data"
  destination = "/data"

[processes]
  app = "/venv/bin/hypercorn -b 0.0.0.0:8000 asgi:app"
  

[[services]]
  processes = ["app"]           # <-- map the service to the process
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[autoscaling]
  min_machines_running = 1
  max_machines_running = 1
