"""add_deleted_at_deleted_by_to_projects

Revision ID: 98d7a73c1cb9
Revises: 6667a76887ac
Create Date: 2025-07-20 23:24:34.506325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d7a73c1cb9'
down_revision: Union[str, None] = '6667a76887ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'deleted_by')
    op.drop_column('projects', 'deleted_at')
    # ### end Alembic commands ###
